version: '3.5'
name: idpcentral-registry

services:
  # Angular app
  webapp:
    container_name: idpcentral-registry-ui
    build: .
    ports:
      - "8050:80"
    restart: always
    volumes:
      - ./apache2/httpd.conf:/usr/local/apache2/conf/httpd.conf
